# Generated by Django 4.2.6 on 2023-10-10 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0001_initial'),
        ('meditation_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meditation_Session',
            new_name='MeditationSession',
        ),
    ]
